import type { ChatConversationItem } from './types';

export const mockChatConversations: ChatConversationItem[] = [
  {
    id: '1',
    name: 'Minh Anh',
    role: 'Bạn thân',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&q=80&w=160',
    presence: 'online',
    lastSeen: 'Đang hoạt động',
    lastMessage: 'Chiều nay mình gọi video nhé!',
    time: '10:24',
    unread: 2,
    pinned: true,
    typing: true,
    hasMoreMessages: true,
    messages: [
      { id: 'm1', sender: 'other', content: 'Chào Nguyên, hôm nay bạn thế nào?', time: '10:18', reactions: [{ type: 'LIKE', count: 1, reactedByMe: true }] },
      { id: 'm2', sender: 'me', content: 'Mình ổn, đang thử giao diện Signify mới nè.', time: '10:20', status: 'seen', edited: true },
      { id: 'm3', sender: 'other', content: 'Trông dễ dùng đó. Chiều nay mình gọi video nhé!', time: '10:24' },
    ],
    sharedFiles: [
      { id: 'f1', name: 'tai-lieu-ngon-ngu-ky-hieu.pdf', mimeType: 'application/pdf', size: 2516582, meta: '2,4 MB · Hôm qua' },
      { id: 'f2', name: 'bang-chu-cai-ky-hieu.png', mimeType: 'image/png', size: 880640, meta: '860 KB · 02/10', url: 'https://images.unsplash.com/photo-1455390582262-044cdead277a?auto=format&fit=crop&q=80&w=900' },
    ],
  },
  {
    id: '2',
    name: 'Bác sĩ Linh',
    role: 'Bác sĩ gia đình',
    avatar: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&q=80&w=160',
    presence: 'online',
    lastSeen: 'Đang hoạt động',
    lastMessage: 'Tôi đã gửi lịch hẹn cho bạn.',
    time: '09:12',
    unread: 0,
    messages: [
      { id: 'm4', sender: 'other', content: 'Tôi đã gửi lịch hẹn cho bạn.', time: '09:12' },
      { id: 'm5', sender: 'me', content: 'Cảm ơn bác sĩ, tôi đã nhận được rồi ạ.', time: '09:15', status: 'seen' },
    ],
    sharedFiles: [{ id: 'f3', name: 'lich-hen.pdf', mimeType: 'application/pdf', size: 348160, meta: '340 KB · Hôm nay' }],
  },
  {
    id: '3',
    name: 'Thầy Hùng',
    role: 'Giáo viên ký hiệu',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=160',
    presence: 'offline',
    lastSeen: 'Hoạt động 2 giờ trước',
    lastMessage: 'Bài tập tuần này nằm trong file nhé.',
    time: 'Hôm qua',
    unread: 0,
    pinned: true,
    messages: [
      { id: 'm6', sender: 'other', content: 'Bài tập tuần này nằm trong file nhé.', time: '20:36' },
    ],
    sharedFiles: [{ id: 'f4', name: 'bai-tap-tuan-4.pdf', mimeType: 'application/pdf', size: 1153434, meta: '1,1 MB · Hôm qua' }],
  },
  {
    id: '4',
    name: 'Nam Phong',
    role: 'Đồng nghiệp',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=160',
    presence: 'offline',
    lastSeen: 'Hoạt động 45 phút trước',
    lastMessage: 'Ok, để mình kiểm tra lại.',
    time: 'T.7',
    unread: 1,
    messages: [
      { id: 'm7', sender: 'me', content: 'Phong kiểm tra giúp mình bản demo nhé.', time: '16:02', status: 'seen' },
      { id: 'm8', sender: 'other', content: 'Ok, để mình kiểm tra lại.', time: '16:04' },
    ],
    sharedFiles: [],
  },
  {
    id: '5',
    name: 'SIGNIFY Support',
    role: 'Hỗ trợ kỹ thuật',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=160',
    presence: 'online',
    lastSeen: 'Luôn sẵn sàng hỗ trợ',
    lastMessage: 'Bạn cần Signify hỗ trợ điều gì?',
    time: 'T.6',
    unread: 0,
    messages: [
      { id: 'm9', sender: 'other', content: 'Xin chào! Bạn cần Signify hỗ trợ điều gì?', time: '08:30' },
    ],
    sharedFiles: [],
  },
];
